server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.17.0.4:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/lib/docker/containers/*/*-json.log

  - job_name: ssh-honeypot
    static_configs:
      - targets:
        - localhost
        labels:
          job: ssh_honeypot
          app: decoy-ssh
          __path__: /decoy-ssh/ssh_honeypot.log

  - job_name: sql-honeypot
    static_configs:
      - targets:
        - locahost
        labels:
          job: sql_honeypot
          app: decoy-sql
          __path__: /sql-logs/general.log
